#!/bin/sh

set -e

HOST=$1

if [ -z "$HOST" ]; then
    echo "Usage: ssh-init [user@]<host>"
    exit 1
fi

IFS=@
set $HOST
ORIG_USER=$USER
USER=$1
HOST=$2

if [ -z "$HOST" ]; then
    HOST=$USER
    USER=$ORIG_USER
fi

if [ "1" = `ssh -oBatchMode=yes $USER@$HOST > /dev/null 2>&1 id && echo 0 || echo 1` ]; then
    echo "Copy SSH key..."
    ssh-copy-id $USER@$HOST > /dev/null
fi

source ~/.ssh-init
ARCHIVE=`basename $REPO`

echo "Install preferences..."
ssh $USER@$HOST "wget -q $REPO ; unzip -q -o $ARCHIVE ; rm $ARCHIVE ; sh $INSTALL_CMD"

if [ ! -z $AUTOLOGIN ]; then
    echo "Autologin..."
    ssh $USER@$HOST
fi
